name: Deploy To Aliyun HK
on:
  push:
    branches: [master]
jobs:
  deploy-aliyun-hk:
    runs-on: ubuntu-latest
    steps:
      name: ssh deploy ${{ secrets.HOST01 }}
      # You may pin to the exact commit or the version.
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
        # 服务器私钥
        SSH_PRIVATE_KEY:  ${{ secrets.HOST01_SSH_PRIVATE_KEY }}
        # 服务器IP
        REMOTE_HOST:  ${{ secrets.HOST01 }}
        # 服务器用户
        REMOTE_USER:  ${{ secrets.HOST01_USER }}
        # 服务器端口
        REMOTE_PORT: ${{ secrets.HOST01_PORT }}
        # 源目录，编译后的目录
        SOURCE: dist
        # 目标目录，服务器上的目录
        TARGET: ${{ secrets.HOST01_PATH }}
        #  rsync 参数
        ARGS: # optional, default is -rltgoDzvO
        # An array of folder to exclude
        EXCLUDE: # optional, default is 


